export const blogs = [
  {
    date: "31 Jan 2023",
    category: "abc",
    img: "./slide.png",
    header: "yoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "def",
    img: "./slide.png",
    header: "yoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "efg",
    img: "./slide.png",
    header: "yoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "abc",
    img: "./slide.png",
    header: "yoga2 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "def",
    img: "./slide.png",
    header: "yoga2 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "efg",
    img: "./slide.png",
    header: "yoga2 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "abc",
    img: "./slide.png",
    header: "yoga3 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "def",
    img: "./slide.png",
    header: "yoga3 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "efg",
    img: "./slide.png",
    header: "yoga3 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "abc",
    img: "./slide.png",
    header: "yoga4 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "def",
    img: "./slide.png",
    header: "yoga4 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
  {
    date: "31 Jan 2023",
    category: "efg",
    img: "./slide.png",
    header: "yoga4 dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    des: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn",
    content: "cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn cmkdsn mckdnws lmdkcwnj kjnjdcwe lkmdncew okindewf mmojindew koidw jmdiew dckowei dwejin jidwe jidnwem ojdnw ojindwekojin oinbfw oijnhdw jnjfwde mjnijwdf miknjwefdyoga dwkn dmwk dmwk dwmk dwmek id dcswjki dwji dfwjid weidnwe nidfew jidwe ijdwe jijdwe jidwe jidjwe jijdwe jifdew jidwefn "
  },
]