export const About = {
  header: "YOGA TEACHER TRAINING IN RISHIKESH INDIA",
  contents: [
            "Namaste. Are you looking for an authentic yoga teacher training ?",
            "India yoga teacher training centre offers a blend of traditional and modern approach of yoga and its practices. Situated at the banks of mother Ganga in world yoga capital “Rishikesh” India yoga teacher training centre offers Multi style 100 Hour yoga TTC in Rishikesh, 200 Hour yoga TTC in Rishikesh, 300 Hour yoga TTC in Rishikesh & 500 Hour yoga TTC in Rishikesh certified with yoga alliance USA which are designed for beginners, intermediate & advanced level students. We offer residential yoga teacher training courses in Rishikesh,India at the most affordable prices. These training courses are widely followed professional yoga teacher training courses which gives seeker an opportunity to register with yoga alliance USA (Largest yoga community).",
            "India yoga teacher training centre focuses on two different yet complimenting styles of yoga practices I.e Ashatnga vinyasa & Vinyasa flow yoga.",
            "Ashtanga means ashta (eight) Anga (limbs) of yoga which has been given to the mankind by Sage patanjali (5th century B.C) where one has been recommended to apply eight different practices in life to gain self realization. Dedicated to the contribution of Sage patanjali we practice a specific form of asana practices known as Ashtanga vinyasa yoga. Ashtanga Vinyasa is style of yoga practice popularised by K.Pattabhi Jois in twentieth century. There are six different well structured series of asanas in Ashtanga Vinyasa where postures are very well arranged and are being performed in synchronization with breathing. India yoga teacher training is the best ashtanga yoga teacher training in Rishikesh India.",
            "Vinyasa flow yoga is more of a dynamic approach of asana practices where no two classes are same. It is a modern way of being creative during yoga practices. One has to improvise and create a flow using all different traditional yoga postures dedicated to the theme of the class.",
            "Vinyasa means to “arrange” where one has to arrange different postures while connecting those with breathing and form a flow which certainly is very interesting and creative way of yoga asana practices. India yoga teacher training centre provides the best vinyasa yoga teacher training in Rishikesh India."
          ]
}